### ISSUE TITLE
ds/concat-in place seems to hang in certain situation

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#129]
While I work with my large 14 GB data file I tried to work with the memory mapped datasets individually vs combing them. 

In total my 14 GB file is read in as 1038 datasets via a modified read-stream-dataset-inplace , which I have in a lazy sequence "dss"

Doing both approaches result in similar performance up to 1000 (out of 1039), like this:

```clojure
 (let [n 1000] (do
 (time (apply merge-with + (map #(frequencies (% "license" ))  (take n dss))))
 (time (frequencies ((apply ds/concat-inplace (take n dss)) "license"))) ))
"Elapsed time: 80784.460589 msecs"
"Elapsed time: 92125.383288 msecs"
```

But in reading more (so n>= 1000), the "concat-inplace" alternative "hangs" for ever.

**Comment by behrica** [comment]
It definitely hangs "for ever" for the "apply ds/concat" case the moment I go from the 1038 to all data sets. (1039)

**Comment by behrica** [comment]
Thread dump

```
2020-08-01 23:56:46
Full thread dump OpenJDK 64-Bit Server VM (25.262-b10 mixed mode):

"Attach Listener" #90 daemon prio=9 os_prio=0 tid=0x00007ff588004000 nid=0x6c10 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"nRepl-session-4bacf1f3-3880-4aca-bb6f-f33fba7a537c" #69 daemon prio=5 os_prio=0 tid=0x00007ff584bdb800 nid=0x62bd runnable [0x00007ff1f30bf000]
   java.lang.Thread.State: RUNNABLE
        at tech.v2.datatype.typecast$__GT_object_reader.doInvoke(typecast.clj:190)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at tech.v2.datatype.readers.concat$fn$reify__39284.read(concat.clj:124)
        at tech.v2.datatype.ObjectReader.get(ObjectReader.java:22)
        at tech.v2.datatype.ListPersistentVector.nth(ListPersistentVector.java:42)
        at clojure.lang.APersistentVector$3.next(APersistentVector.java:308)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$frequencies.invokeStatic(core.clj:7203)
        at clojure.core$frequencies.invoke(core.clj:7203)
        at tech.libs.big_csv$eval44882.invokeStatic(form-init4634039279961396652.clj:1)
        at tech.libs.big_csv$eval44882.invoke(form-init4634039279961396652.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7177)
        at clojure.lang.Compiler.eval(Compiler.java:7132)
        at clojure.core$eval.invokeStatic(core.clj:3214)
        at clojure.core$eval.invoke(core.clj:3210)
        at clojure.main$repl$read_eval_print__9086$fn__9089.invoke(main.clj:437)
        at clojure.main$repl$read_eval_print__9086.invoke(main.clj:437)
        at clojure.main$repl$fn__9095.invoke(main.clj:458)
        at clojure.main$repl.invokeStatic(main.clj:458)
        at clojure.main$repl.doInvoke(main.clj:368)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:79)
        at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
        at nrepl.middleware.interruptible_eval$interruptible_eval$fn__921$fn__925.invoke(interruptible_eval.clj:142)
        at clojure.lang.AFn.run(AFn.java:22)
        at nrepl.middleware.session$session_exec$main_loop__1022$fn__1026.invoke(session.clj:171)
        at nrepl.middleware.session$session_exec$main_loop__1022.invoke(session.clj:170)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)

"tech.resource.gc ref thread" #18 daemon prio=5 os_prio=0 tid=0x00005621de9cf000 nid=0x5cf4 in Object.wait() [0x00007ff5688fc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000086ee85e8> (a java.lang.ref.ReferenceQueue$Lock)
        at tech.resource.gc$watch_reference_queue$fn__15012.invoke(gc.clj:28)
        at tech.resource.gc$watch_reference_queue.invokeStatic(gc.clj:24)
        at tech.resource.gc$watch_reference_queue.invoke(gc.clj:22)
        at tech.resource.gc$start_reference_thread$fn__15024.invoke(gc.clj:48)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)

"LArray-GC" #17 daemon prio=5 os_prio=0 tid=0x00005621dee36800 nid=0x5cf3 in Object.wait() [0x00007ff5689fd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000089bf7748> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000089bf7748> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at xerial.larray.buffer.DefaultMemoryAllocator$1.run(DefaultMemoryAllocator.java:32)
        at java.lang.Thread.run(Thread.java:748)

"nRepl-session-54635c4d-0250-488c-9063-6e9ad165d20d" #13 daemon prio=5 os_prio=0 tid=0x00007ff56c012000 nid=0x5c96 waiting on condition [0x00007ff57ed92000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000086224030> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at nrepl.middleware.session$session_exec$main_loop__1022.invoke(session.clj:168)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)

"clojure-agent-send-off-pool-3" #11 prio=5 os_prio=0 tid=0x00007ff5b8f26800 nid=0x5c94 waiting on condition [0x00007ff57ef94000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000085d79db8> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at nrepl.transport$fn_transport$fn__385.invoke(transport.clj:62)
        at nrepl.transport.FnTransport.recv(transport.clj:43)
        at nrepl.transport.FnTransport.recv(transport.clj:42)
        at nrepl.server$handle.invokeStatic(server.clj:26)
        at nrepl.server$handle.invoke(server.clj:22)
        at nrepl.server$accept_connection$fn__1099.invoke(server.clj:46)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"clojure-agent-send-off-pool-2" #10 prio=5 os_prio=0 tid=0x00007ff5b8f1f800 nid=0x5c91 runnable [0x00007ff57f095000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        - locked <0x0000000086224ba0> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:139)
        at nrepl.bencode$read_byte.invokeStatic(bencode.clj:87)
        at nrepl.bencode$read_byte.invokePrim(bencode.clj)
        at nrepl.bencode$read_token.invokeStatic(bencode.clj:239)
        at nrepl.bencode$read_token.invoke(bencode.clj:237)
        at nrepl.bencode$read_bencode.invokeStatic(bencode.clj:257)
        at nrepl.bencode$read_bencode.invoke(bencode.clj:254)
        at nrepl.transport$bencode$fn__427$fn__428.invoke(transport.clj:108)
        at nrepl.transport$bencode$fn__427.invoke(transport.clj:108)
        at nrepl.transport$fn_transport$fn__383.invoke(transport.clj:55)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"clojure-agent-send-off-pool-0" #8 prio=5 os_prio=0 tid=0x00007ff5b8de7000 nid=0x5c8f runnable [0x00007ff57f52b000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:560)
        at java.net.ServerSocket.accept(ServerSocket.java:528)
        at nrepl.server$accept_connection.invokeStatic(server.clj:41)
        at nrepl.server$accept_connection.invoke(server.clj:37)
        at nrepl.server$accept_connection$fn__1101.invoke(server.clj:50)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007ff5b80c5800 nid=0x5c8d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007ff5b80c2800 nid=0x5c8c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007ff5b80bf800 nid=0x5c8b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007ff5b80bd800 nid=0x5c8a runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007ff5b808b000 nid=0x5c89 in Object.wait() [0x00007ff5a4efb000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000084393170> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007ff5b8086800 nid=0x5c88 in Object.wait() [0x00007ff5a4ffc000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000000843931c8> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007ff5b8014000 nid=0x5c81 waiting on condition [0x00007ff5be52c000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000085c53f70> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at clojure.core$promise$reify__8501.deref(core.clj:7109)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at user$eval1894.invokeStatic(form-init4634039279961396652.clj:1)
        at user$eval1894.invoke(form-init4634039279961396652.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7177)
        at clojure.lang.Compiler.eval(Compiler.java:7167)
        at clojure.lang.Compiler.eval(Compiler.java:7167)
        at clojure.lang.Compiler.eval(Compiler.java:7167)
        at clojure.lang.Compiler.load(Compiler.java:7636)
        at clojure.lang.Compiler.loadFile(Compiler.java:7574)
        at clojure.main$load_script.invokeStatic(main.clj:475)
        at clojure.main$init_opt.invokeStatic(main.clj:477)
        at clojure.main$init_opt.invoke(main.clj:477)
        at clojure.main$initialize.invokeStatic(main.clj:508)
        at clojure.main$null_opt.invokeStatic(main.clj:542)
        at clojure.main$null_opt.invoke(main.clj:539)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)

"VM Thread" os_prio=0 tid=0x00007ff5b807d000 nid=0x5c87 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007ff5b8028800 nid=0x5c82 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007ff5b802a800 nid=0x5c83 runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007ff5b80c8000 nid=0x5c8e waiting on condition

JNI global references: 290

```

**Comment by cnuernber** [comment]
I think it is just really slow.  It is doing a O(N) search to find which sub-reader corresponds to the appropriate indexes and then goes from there.  Even if you sort it you get log(N) for a binary search.  I think for really large datasets like this, we have to implement a frequencies primitive at the dataset level or concat has to be smarter.  

Solid issue, this is for sure a problem.

**Comment by behrica** [comment]
This does not match, what I saw.
Using "nearly" the whole 14 GB,
it was still very fast. (between one and 2 minutes for the same task)

Then by getting all (14 GB + a bit), it went from 1:30 minutes to more then 10 minutes before I killed it)

I saw the "hanging" precisely as I went from 1038 (out of 1039) datasets to 1039/1039.

**Comment by cnuernber** [comment]
huh.  Do datasets up to 1038 have the same row lengths?  If so there is an optimization that makes it `(quot idx n-datasets)` to find the dataset and `(rem idx n-datasets) to find the specific index and thus the lookup for Y datasets is more or less instant.  As soon as any dataset has a different length that doesn't work but I guess then I could under-the-covers concatenate runs of readers that have the same element count into optimized groups...

**Comment by behrica** [comment]
I am pretty sure, that all previous datasets have indeed the same length.
I created the underlying arrow file in batches , which have constant size.
Only the last is smaller

**Comment by cnuernber** [comment]
This is due to the indexing algorithm.  `concat-copying` will work up to your RAM threshold and after that you will need to just work with a sequence of datasets.  

Building the real abstraction for big data (sequence of datasets) is a task for another project.
