### ISSUE TITLE
fastexcel raises NullPointerException 

### ISSUE THREAD

**Issue by DavidVujic** [techascent/tech.ml.dataset#238]
I think this is where the exception is raised:
https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/libs/fastexcel.clj#L96

I'm too unfamiliar with the Java interop syntax to suggest a solution or submit a PR. Should it do some nil checks before calling the `hasNext` function?

Stack trace
```
java.lang.NullPointerException: null
    at org.dhatim.fastexcel.reader.RowSpliterator.next(RowSpliterator.java:85)
    at org.dhatim.fastexcel.reader.RowSpliterator.tryAdvance(RowSpliterator.java:47)
    at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
    at tech.v3.libs.fastexcel$wrap_sheet$reify$reify__45416.hasNext(fastexcel.clj:96)
    at clojure.lang.RT.chunkIteratorSeq(RT.java:517)
    at clojure.core$iterator_seq.invokeStatic(core.clj:5729)
    at clojure.core$iterator_seq.invoke(core.clj:5721)
    at tech.v3.dataset.io.spreadsheet$sheet__GT_dataset.invokeStatic(spreadsheet.clj:25)
    at tech.v3.dataset.io.spreadsheet$sheet__GT_dataset.invoke(spreadsheet.clj:16)
...
```

**Comment by cnuernber** [comment]
The crash is in fastexcel code specifically in it's rowspliterator implementation of [tryAdvance](https://github.com/dhatim/fastexcel/blob/0da9620b7dab255a58a350cc772c4c78338a181b/fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/RowSpliterator.java#L44).  They only catch xml row stream exception, not null ptr.

That is a pretty old version of fastexcel though; they have (many) newer versions.  Perhaps upgrading fastexcel will fix the issue and I can also catch an exception during hasNext and return false.

**Comment by DavidVujic** [comment]
That would be great @cnuernber!

**Comment by cnuernber** [comment]
Tried both.  Upgrading fastexcel may cause other issues for your codebase so beware :-).

**Comment by DavidVujic** [comment]
Great, thanks!
